[package]
name = "pdf-console-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.29"
clap = { version = "4.0", features = ["derive"] }
kurbo = "0.8.3"
regex="1"
