name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: true

      - run: |
          zip --junk-paths ${{ matrix.target }} target/${{ matrix.target }}/release/pdf-console-editor{,.exe}

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.target }}
          path: ${{ matrix.target }}.zip

  upload-assets:
    name: Upload Assets
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ always() }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: Upload prebuild asset
        uses: icrawl/action-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: '*/*.zip'
